spring:
  application:
    name: zjz-ai-agent
  profiles:
    active: local
  ai:
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
            schema: classpath:schema/schema.sql
    vectorstore:
      pgvector:
        index-type: HNSW
        dimensions: 1024
        distance-type: COSINE_DISTANCE
        max-document-batch-size: 10 # Optional: Maximum number of documents per batch
    mcp:
      client:
        enabled: true
        type: ASYNC
        request-timeout: 120s
        toolcallback:
          enabled: true
        #stdio
        #stdio:
        #  servers-configuration: classpath:mcp-servers.json
        #sse
        sse:
          connections:
            servers1:
              url: http://47.120.65.115:8127
server:
  port: 8081
  servlet:
    context-path: /api
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: org.example.zjzaiagent.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
